# Generated by Django 5.0.3 on 2024-03-14 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='news_count',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='news_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='news_title',
            field=models.CharField(max_length=50),
        ),
    ]
