# Generated by Django 5.0.3 on 2024-03-15 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_date',
            field=models.DateField(default=datetime.date(2024, 3, 15)),
        ),
    ]
