# Generated by Django 5.0.3 on 2024-03-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsmodel_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_date',
            field=models.DateField(),
        ),
    ]
