# Generated by Django 5.0.3 on 2024-03-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsmodel_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_country', models.CharField(max_length=30)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('news_image', models.FileField(upload_to='news_images')),
                ('news_created_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('news_image', models.FileField(upload_to='news_images')),
                ('news_created_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Tech_science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_country', models.CharField(max_length=30)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('news_image', models.FileField(upload_to='news_images')),
                ('news_created_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='World_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_country', models.CharField(max_length=30)),
                ('news_date', models.DateField()),
                ('news_description', models.TextField()),
                ('news_image', models.FileField(upload_to='news_images')),
                ('news_created_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel')),
            ],
        ),
    ]
