# Generated by Django 5.0.3 on 2024-03-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_cultural_national_tech_science_world_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tech_science',
            new_name='TechScience',
        ),
        migrations.RenameModel(
            old_name='World_news',
            new_name='WorldNews',
        ),
        migrations.AlterModelOptions(
            name='cultural',
            options={'verbose_name': 'Cultural', 'verbose_name_plural': 'Cultural News'},
        ),
        migrations.AlterModelOptions(
            name='national',
            options={'verbose_name': 'National', 'verbose_name_plural': 'National News'},
        ),
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='techscience',
            options={'verbose_name': 'Tech & Science', 'verbose_name_plural': 'Tech & Science News'},
        ),
        migrations.AlterModelOptions(
            name='worldnews',
            options={'verbose_name': 'World News', 'verbose_name_plural': 'World News'},
        ),
    ]
