# Generated by Django 5.0.3 on 2024-03-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_tech_science_techscience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='National',
            new_name='National_url',
        ),
    ]
